package com.teclavya.notification.lifecycle.analytics;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Spring Data repository for {@link LifecycleEvent}.
 *
 * <p>All finders are generated by Spring Data from method names; no custom JPQL needed for MVP.
 */
@Repository
public interface LifecycleEventRepository extends JpaRepository<LifecycleEvent, UUID> {

    /**
     * Find events by event type within a created-at range (inclusive start, exclusive end).
     *
     * @param eventType  the canonical event type string
     * @param from       range start (inclusive)
     * @param to         range end (exclusive)
     */
    List<LifecycleEvent> findByEventTypeAndCreatedAtBetween(
            String eventType, Instant from, Instant to);

    /**
     * Find all events for a given student, newest first.
     *
     * @param studentId the student identifier
     */
    List<LifecycleEvent> findByStudentIdOrderByCreatedAtDesc(String studentId);

    /**
     * Find all events linked to a specific lifecycle message.
     *
     * @param messageId UUID of the lifecycle_message_review_queue row
     */
    List<LifecycleEvent> findByMessageId(UUID messageId);
}
