package com.teclavya.notification.entities;

public enum NotificationType {
    // Existing
    STREAK_AT_RISK,
    DAILY_CHALLENGE_AVAILABLE,
    REVIEW_ITEMS_DUE,
    LEAGUE_POSITION_CHANGE,
    FRIEND_ACTIVITY,
    GOAL_COMPLETED,
    WEEKLY_SUMMARY,
    COMEBACK_INCENTIVE,
    ACHIEVEMENT_UNLOCKED,
    GENERAL,
    // New platform event types
    ASSESSMENT_GRADED,
    PR_REVIEWED,
    MENTOR_REPLIED,
    AI_RESPONSE_DONE,
    COHORT_POST_CREATED,
    COHORT_POST_REPLY,
    SESSION_BOOKED,
    SESSION_REMINDER
} 
    CONTENT_REQUEST_STATUS_CHANGE,
    CONTENT_REQUEST_LIVE,
    PATH_PIONEER_BADGE,
    GENERAL
}
