server:
  port: 0
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
application:
  cors: http://localhost:3000
  jwt:
    secret: 4D6251655468576D5A7134743777217A25432A462D4A614E645267556B587032
    expiration: 86400000
  notification:
    max-push-per-day: 3
    max-email-per-day: 1
    quiet-hours-start: 22
    quiet-hours-end: 7